### ISSUE TITLE
I was trying to delete a proj...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#596] opened 2016-05-18 19:40 UTC
Notes
======
I was trying to delete a project. After clicking the CONFIRM link, it is shaded but nothing happens.

Environment
======
Environment Key | Value
:--: | :--:
Version |8.0.0
Operating System | Darwin
Platform | darwin
Release | 15.4.0
Architecture | x64

Log History
======
```javascript
No log file.
```

**Comment by cckozie** [comment] 2016-05-18 19:45
Even after closing and reopening the app, I still cannot delete the project.
[en-x-demo1_tit_text_ulb_no_delete.tstudio.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/271265/en-x-demo1_tit_text_ulb_no_delete.tstudio.zip)

**Comment by cdwhitfield73** [comment] 2016-05-23 23:34
Added steps to check for and catch errors in deleting projects and send messages back to the user so that the app will complete the task, pass or fail, and not just hang up

**Comment by cdwhitfield73** [comment] 2016-06-10 18:28
The root cause of this hang up was the NodeGit issues.  Deleting should always work now.

**Closed** 2016-06-27 16:07 UTC
Labels: 8.0.0, bug report, QA Passed
