### ISSUE TITLE
Fix Publish Implementation

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-desktop#192] opened 2015-12-15 16:55 UTC
The push phase of the publishing failed at the India workshop.

**Comment by vleong2332** [comment] 2015-12-15 17:25
I'm unsuccessful in reproducing this error on my 64-bit windows. Were you able to determine if it was installed correctly along with git?

**Comment by cdwhitfield73** [comment] 2015-12-15 17:50
Pushing works for me also using Windows 10 and Ubuntu 14

**Comment by vleong2332** [comment] 2015-12-15 18:07
@jag3773 do you have more details on this?

**Comment by jag3773** [comment] 2015-12-15 19:38
Unfortunately no, I suspect it was Windows 7 64 bit though.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by PhotoNomad0** [comment] 2015-12-15 22:33
I have Windows 7 64-bit.  When I do publish, it hangs on dialog "Uploading Project.  Please wait..."

I do have git installed from github.

**Comment by tjklemz** [comment] 2015-12-15 22:41
Looks like there are two separate issues depending on which code the user has. If the user downloaded the last GitHub release, there is a Git issue where it fails to push. If the user has the latest code, the push works but is (apparently) not showing up on the server.

I've tested the push on the following systems, and they push successfully with the latest code and appropriate environment setup:
- Mac OS X El Capitan (requires Git to be installed through Xcode or Git website)
- Ubuntu 14 and 15 (requires the setup.sh to be run per the install instructions)
- Debian (latest, requires installing Git from source)
- Windows 7 32 bit (requires Git to be installed from Git website and merging of Unix tools/Windows CMD)

Git must be at least version 2.3 in order to work properly for tsDesktop. In the future, Git and its dependencies will be bundled with the app.

We are planning to have all the publish issues (including the server issue) resolved by this Friday. Not sure when we'll have Git bundled, but I'm looking into it.

**Comment by neutrinog** [comment] 2015-12-15 22:47
There is another issue in that the content is not showing up on the server even after the publish completes successfully in the app.

For example create an obs translation in en-x-demo1, add some text, publish it and look at  https://door43.org/en-x-demo1/obs/01?do=door43gitmerge-crawl. There should be a red badge on the icon indicated below that displays the number of changes pending.
![screenshot_121515_021511_pm](https://cloud.githubusercontent.com/assets/166412/11826432/4120d130-a33a-11e5-9838-f4ae97fefb7e.jpg)

**Comment by tjklemz** [comment] 2015-12-18 19:59
Simply, most of this issue centers around not having Git bundled.

I've been working on fixing this, and I think I have nodegit working with Electron. This means Git/SSH/etc will all be bundled with the app. No more environment setup!

More details soon...

**Closed** 2015-12-19 05:04 UTC
Labels: bug, Priority
