### ISSUE TITLE
Allow Font to be Set by User

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#395] opened 2016-03-02 00:36 UTC
For more details refer to the specs at: https://github.com/unfoldingWord-dev/ts-requirements/issues/32

**Comment by cdwhitfield73** [comment] 2016-05-26 21:04
This has been done.  Basically a duplicate of issue #591.

**Comment by neutrinog** [comment] 2016-06-10 22:10
@cdwhitfield73 this works but it can take awhile to load the dialog. If the user gets board (like I did at first) and tries to click again it multiple dialogs will get stacked.

**Comment by cckozie** [comment] 2016-06-13 15:26
There needs to be a spinning wheel or some other indication that the available font list is being loaded when the user clicks either the Target Translation Font or Source Translation Font "button". It takes 2-3 seconds on the Lenovo for the font list to come up which makes it look like changing the font is not an option or it is broken, and like me, the user will probably click somewhere else which then queues up the clicks.. Something similar to what happens when the Backup Location is clicked would be appropriate.

**Closed** 2016-06-27 16:07 UTC
Labels: QA Passed
