### ISSUE TITLE
App can hang when starting if backup location is on an external drive

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#582] opened 2016-05-11 22:35 UTC
@cckozie commented on [Wed May 11 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/108)

To reproduce this problem:
- Set the backup location to a USB flash drive
- Backup a project to the drive
- Close the app
- Remove the USB flash drive and restart the app
- Force the app to close after it hangs
- Reinsert the flash drive and restart the app. 
The app will still hang and I can't find a way to get it to work again without first deleting the Local Storage folder.

**Comment by vleong2332** [comment] 2016-05-24 02:04
@cckozie, did it hang on "initializing"?

**Comment by vleong2332** [comment] 2016-05-24 02:18
@neutrinog, the problem is the app trying to create a directory on a drive/location that's non-existent. In this case, should we reset the backup location to the default one?

**Comment by neutrinog** [comment] 2016-05-24 14:52
@vleong2332 no if the backup location does not exist then a message should be displayed to the user stating that their backup location no longer exists. This will give them the opportunity to plug it back in or change it.

**Comment by vleong2332** [comment] 2016-05-27 03:31
The fix for this is in @cdwhitfield73's `workspace` branch.

**Closed** 2016-06-27 16:07 UTC
Labels: bug, QA Passed
