### ISSUE TITLE
msvcp120.dll is missing during install

### ISSUE THREAD

**Issue by markellishancock** [unfoldingWord-dev/ts-desktop#437] opened 2016-03-05 21:45 UTC
one single issue with translation studio: msvcp120.dll is missing. What can I do to fix that?

Just Install the new release v4.1 but still having the same problem.
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [ ] Check that a similar issue has not already been opened.

**Comment by markellishancock** [comment] 2016-03-05 23:07
Victor was able to correct the issue by installing vcredist_x64 from Microsoft website and it is now working well.

Ken, this is a new way we can resolve it.

**Comment by neutrinog** [comment] 2016-03-29 16:56
duplicate of #476

**Closed by neutrinog** 2016-03-29 16:56 UTC
