### ISSUE TITLE
having difficulty updating ta...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#1099] opened 2017-03-04 13:50 UTC
Notes
======
having difficulty updating target languages

Environment
======
Environment Key | Value
:--: | :--:
Version |11.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript
2016-11-15 16:6:15 E/ts-dashboard.html:870:2: Error on startup
	Git is not installed. It is required to run tStudio Desktop.
2016-11-15 16:11:8 I/ts-dashboard.html:837:3: 
	Git Version 2.9.2.windows.1
2016-11-15 16:11:8 I/migrator.js:31:2: Migrated projects
	[]
2016-11-18 14:14:24 I/ts-dashboard.html:837:3: 
	Git Version 2.9.2.windows.1
2016-11-18 14:14:24 I/migrator.js:31:2: Migrated projects
	[]
2016-11-18 14:31:51 E/ts-dashboard.html:335:3: Update Failed
	Could not update language list
2016-11-19 11:50:19 I/ts-dashboard.html:837:3: 
	Git Version 2.9.2.windows.1
2016-11-19 11:50:19 I/migrator.js:31:2: Migrated projects
	[]
2016-11-19 11:53:24 I/ts-dashboard.html:837:3: 
	Git Version 2.9.2.windows.1
2016-11-19 11:53:24 I/migrator.js:31:2: Migrated projects
	[]
2016-11-23 12:38:16 I/ts-dashboard.html:837:3: 
	Git Version 2.9.2.windows.1
2016-11-23 12:38:17 I/migrator.js:31:2: Migrated projects
	[
	  "pt-br_job_text_reg"
	]
2017-02-28 11:55:26 I/ts-dashboard.html:837:3: 
	Git Version 2.9.2.windows.1
2017-02-28 11:55:27 I/migrator.js:31:2: Migrated projects
	[
	  "pt-br_hag_text_ulb",
	  "pt-br_job_text_reg"
	]
2017-02-28 11:55:50 E/projects.js:578:3: 
	Error: Command failed: C:\Program Files (x86)\translationStudio\resources\app\node_modules\trash\lib\win-trash.exe C:\Users\WABW-005\AppData\Local\translationstudio\targetTranslations\pt-br_job_text_reg
	
2017-02-28 11:55:50 E/ts-dashboard.html:358:3: Delete Failed
	Unable to delete file at this time. You may need to restart the app first.
2017-02-28 11:56:4 E/projects.js:578:3: 
	Error: Command failed: C:\Program Files (x86)\translationStudio\resources\app\node_modules\trash\lib\win-trash.exe C:\Users\WABW-005\AppData\Local\translationstudio\targetTranslations\pt-br_job_text_reg
	
2017-02-28 11:56:4 E/ts-dashboard.html:358:3: Delete Failed
	Unable to delete file at this time. You may need to restart the app first.
2017-02-28 12:28:40 I/ts-dashboard.html:1202:3: 
	Git Version 2.9.2.windows.1
2017-02-28 12:28:40 I/migrator.js:31:2: Migrated projects
	[]
2017-03-04 14:21:23 I/ts-dashboard.html:1202:3: 
	Git Version 2.9.2.windows.1
2017-03-04 14:21:24 I/migrator.js:31:2: Migrated projects
	[]
2017-03-04 14:27:6 I/ts-dashboard.html:1202:3: 
	Git Version 2.9.2.windows.1
2017-03-04 14:27:6 I/migrator.js:31:2: Migrated projects
	[]
2017-03-04 14:28:39 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input
2017-03-04 14:31:16 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input
2017-03-04 14:32:42 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input
2017-03-04 14:34:36 E/ts-dashboard.html:447:3: Update Failed
	Error: read ECONNRESET
2017-03-04 14:36:18 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input
2017-03-04 14:40:15 E/ts-dashboard.html:447:3: Update Failed
	Error: read ECONNRESET
2017-03-04 14:42:18 E/ts-dashboard.html:447:3: Update Failed
	Error: read ECONNRESET
2017-03-04 14:48:1 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input
2017-03-04 15:0:13 I/ts-dashboard.html:1202:3: 
	Git Version 2.9.2.windows.1
2017-03-04 15:0:14 I/migrator.js:31:2: Migrated projects
	[]
2017-03-04 15:2:55 E/ts-dashboard.html:447:3: Update Failed
	Error: read ECONNRESET
2017-03-04 15:8:7 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input
2017-03-04 15:10:48 E/ts-dashboard.html:447:3: Update Failed
	Error: read ECONNRESET
2017-03-04 15:21:15 I/ts-dashboard.html:1202:3: 
	Git Version 2.9.2.windows.1
2017-03-04 15:21:15 I/migrator.js:31:2: Migrated projects
	[]
2017-03-04 15:25:29 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input
2017-03-04 15:35:51 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input
2017-03-04 15:37:56 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input
2017-03-04 15:40:15 E/ts-dashboard.html:499:3: Update Failed
	Error: socket hang up
2017-03-04 15:41:6 E/ts-dashboard.html:447:3: Update Failed
	Error: connect ETIMEDOUT 104.197.64.185:443
2017-03-04 15:43:23 E/ts-dashboard.html:499:3: Update Failed
	Error: socket hang up
2017-03-04 15:52:18 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input

```

**Comment by cdwhitfield73** [comment] 2017-03-06 16:55
Based on comments in slack, this issue was caused by slow or unreliable internet connection and has been resolved.  Closing issue.

**Closed** 2017-03-06 16:55 UTC
Labels: 11.0.0, bug report
