### ISSUE TITLE
Project Delete Modal pauses on close

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-desktop#923] opened 2016-12-02 19:32 UTC
When I use the information section (from the home page) for a project and choose to delete - the deletion continues fine. When the modal shows there is a delay (a couple of seconds) before the 'close' link is active (turns blue). Is that by design?
![close on project delete pauses](https://cloud.githubusercontent.com/assets/9850185/20847444/1885f994-b89c-11e6-902e-dad6d737d3c6.png)

**Comment by cdwhitfield73** [comment] 2016-12-05 19:42
No, this was not by design.  It is the consequence of some code that is not functioning "optimally".  I will fix it!

**Comment by ChrisJarka** [comment] 2016-12-06 15:02
@cckozie could not replicate. But, I have 24 open projects in tS-D and he will test with 20-30 projects to see if he experiences the same lag time.

**Comment by cckozie** [comment] 2016-12-08 17:40
Appears to be fixed in build 79.

**Closed** 2017-02-09 20:44 UTC
Labels: QA Passed
