### ISSUE TITLE
only 3 target languages after...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#1101] opened 2017-03-04 14:24 UTC
Notes
======
only 3 target languages after update - all qaa-x

Environment
======
Environment Key | Value
:--: | :--:
Version |11.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript
2016-11-15 16:15:24 E/ts-dashboard.html:870:2: Error on startup
	Git is not installed. It is required to run tStudio Desktop.
2016-11-15 09:22:31 I/ts-dashboard.html:837:3: 
	Git Version 2.9.2.windows.1
2016-11-15 09:22:31 I/migrator.js:31:2: Migrated projects
	[]
2016-11-18 14:21:17 I/ts-dashboard.html:837:3: 
	Git Version 2.9.2.windows.1
2016-11-18 14:21:17 I/migrator.js:31:2: Migrated projects
	[]
2016-11-19 11:50:10 I/ts-dashboard.html:837:3: 
	Git Version 2.9.2.windows.1
2016-11-19 11:50:10 I/migrator.js:31:2: Migrated projects
	[]
2016-11-19 14:48:43 E/ts-translate.html:488:4: Error backing up translation
	Error creating backup: [object Object]
2016-11-19 14:52:13 I/ts-dashboard.html:837:3: 
	Git Version 2.9.2.windows.1
2016-11-19 14:52:13 I/migrator.js:31:2: Migrated projects
	[]
2016-11-19 16:30:5 I/ts-dashboard.html:837:3: 
	Git Version 2.9.2.windows.1
2016-11-19 16:30:5 I/migrator.js:31:2: Migrated projects
	[
	  "sbs_mat_text_reg"
	]
2016-11-20 11:22:31 I/ts-dashboard.html:837:3: 
	Git Version 2.9.2.windows.1
2016-11-20 11:22:31 I/migrator.js:31:2: Migrated projects
	[
	  "sbs_mat_text_reg"
	]
2017-02-28 12:3:32 I/ts-dashboard.html:837:3: 
	Git Version 2.9.2.windows.1
2017-02-28 12:3:33 I/migrator.js:31:2: Migrated projects
	[
	  "sbs_mat_text_reg",
	  "sbs_php_text_reg"
	]
2017-02-28 12:4:1 E/projects.js:578:3: 
	Error: Command failed: C:\Program Files (x86)\translationStudio\resources\app\node_modules\trash\lib\win-trash.exe C:\Users\WABW-004\AppData\Local\translationstudio\targetTranslations\sbs_mat_text_reg
	
2017-02-28 12:4:1 E/ts-dashboard.html:358:3: Delete Failed
	Unable to delete file at this time. You may need to restart the app first.
2017-02-28 12:4:17 E/projects.js:578:3: 
	Error: Command failed: C:\Program Files (x86)\translationStudio\resources\app\node_modules\trash\lib\win-trash.exe C:\Users\WABW-004\AppData\Local\translationstudio\targetTranslations\sbs_mat_text_reg
	
2017-02-28 12:4:17 E/ts-dashboard.html:358:3: Delete Failed
	Unable to delete file at this time. You may need to restart the app first.
2017-02-28 12:4:30 E/projects.js:578:3: 
	Error: Command failed: C:\Program Files (x86)\translationStudio\resources\app\node_modules\trash\lib\win-trash.exe C:\Users\WABW-004\AppData\Local\translationstudio\targetTranslations\sbs_mat_text_reg
	
2017-02-28 12:4:30 E/ts-dashboard.html:358:3: Delete Failed
	Unable to delete file at this time. You may need to restart the app first.
2017-03-04 14:40:45 I/ts-dashboard.html:1202:3: 
	Git Version 2.9.2.windows.1
2017-03-04 14:40:45 I/migrator.js:31:2: Migrated projects
	[]
2017-03-04 14:47:20 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input
2017-03-04 15:10:29 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input
2017-03-04 15:11:15 E/ts-dashboard.html:447:3: Update Failed
	Error: socket hang up
2017-03-04 15:51:3 I/ts-dashboard.html:1202:3: 
	Git Version 2.9.2.windows.1
2017-03-04 15:51:3 I/migrator.js:31:2: Migrated projects
	[]
2017-03-04 15:54:38 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input
2017-03-04 15:56:22 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input
2017-03-04 16:9:22 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input
2017-03-04 16:24:33 E/ts-dashboard.html:447:3: Update Failed
	Error: read ECONNRESET
2017-03-04 16:25:57 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input

```

**Comment by cdwhitfield73** [comment] 2017-03-06 16:56
Based on comments in slack, this issue was caused by slow or unreliable internet connection and has been resolved.  Closing issue.

**Closed** 2017-03-06 16:56 UTC
Labels: 11.0.0, bug report
