### ISSUE TITLE
Backup to GOGS

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#452] opened 2016-03-10 17:55 UTC
users will be able to backup individual translations from the backup menu. We'll need to update the backup button so that it opens a dialog with options for backing up instead of just opening a file browser.

The backup works just like publishing (in that it's a push). The difference is that the repo is *not* tagged and the user does not need to review anything.

**Comment by cckozie** [comment] 2016-05-18 20:27
See #598. Project attached.
[en-x-demo1_obs_text_obs.tstudio.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/271346/en-x-demo1_obs_text_obs.tstudio.zip)

**Comment by cdwhitfield73** [comment] 2016-05-19 18:06
added a more user friendly error message for this failure.  However, code is working as designed for now.  Cannot upload a project if one already exists on server with a different git history.

**Comment by cckozie** [comment] 2016-05-24 22:41
I agree that the error message is now "more user friendly", but it still doesn't give them any idea of how to solve the problem. That will likely result first in frustration, then a conversation (interruption) with someone to get some help. 
It looks like it will upload if I use a different door43 account. Maybe we should suggest in the error message, or behind a "Details" link on the message, to change door43 account before uploading, then possibly do a merge with the project already there under the current account.
I'm going to ping Klappy to get his input on how to handle this.

**Comment by cdwhitfield73** [comment] 2016-05-25 15:31
Suggesting that the user change to a different account seems like a bad idea, and is not necessary.  They have the ability to import a project from door43 and merge it with a local project.  So if they can't upload because another project exists, they can either delete that project from their account, or import and merge it with the existing one in the app first and then re-upload it

**Comment by neutrinog** [comment] 2016-05-25 21:36
@cdwhitfield73 the app should automatically pull down and merge the project in their door43 account with the one locally and then attempt to push again.

**Comment by cdwhitfield73** [comment] 2016-05-25 21:46
yes, I am aware that this is the ultimate goal, but this functionality has not been implemented yet and is in a separate issue.  For now, whether uploading or backing up to the server, it will not allow it if the git history does not match.  This is not a fail of this issue.  This is just future improvements that have not been made yet.

**Comment by neutrinog** [comment] 2016-05-25 21:54
@cckozie @cdwhitfield73 is correct. When this issue was originally created we did not have any specification on how to handle conflicts with the server. I propose this issue be marked as resolved and a new one opened to finished implementing the spec described at . https://github.com/unfoldingWord-dev/ts-requirements/wiki/Publishing

**Comment by RRohrssen** [comment] 2016-05-26 16:30
This functionality is essentially done. We need another issue to tackle merging the project if it is found to exist on the server.

https://github.com/unfoldingWord-dev/ts-desktop/issues/603

**Comment by RRohrssen** [comment] 2016-05-26 16:31
@cckozie do you agree with the above comment?

**Comment by cckozie** [comment] 2016-05-31 13:54
Issue #615 has been created to handle the merge.

**Closed by cckozie** 2016-05-31 13:54 UTC
Labels: QA Passed
