### ISSUE TITLE
Cursor up/down and page up/down keys do not work properly

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#973] opened 2016-12-19 21:05 UTC
@cckozie commented on [Mon Dec 19 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/199)

There was a problem in previous versions of the down arrow not working properly when editing the text in a chunk. The up, left, and right cursor keys did seem to work properly, as did using the cursor keys to scroll the screen when not editing inside of a chunk.
In V11, there are some new issues. (I'm doing these tests in a Psalms project with build 86)
1. If I open a project and click on a chunk, sometimes the cursor arrow keys work as expected, but often if I click on a chunk and then press and hold the up or down arrow key, it will move only one time and then freeze. When this happens on a Windows machine, it looks like it is buffering the keyboard input because a while after releasing the arrow key, the screen will scroll to a new place. On the Mac, it seems to just ignore the additional arrow key input as it just stays on the displayed chunk(s) at the time I release the key. This behavior is intermittent on both Windows and OSX.
2. On my Mac. After opening a chunk in edit mode and using the cursor keys to try to move around in the text, I start seeking some strange behaviors. Sometimes if I down arrow several times, the screen will scroll out of the chunk and down some number of chunks. If I use the track pad to scroll back to the chunk being edited and click in that chunk, it sends me back to the chuck I just navigated from. Sometimes it will set the cursor in the editing chunk, but then using the keyboard or track pad is significantly delayed and I am not able to control the scrolling using the trackpad except it I try to scroll VERY slowly.
In this scenario on Windows I do not see the situation where the cursor leaves the chunk being edited and then scrolling the screen as often, or that using the trackpad does not work properly, but I do see a significant delay when typing data in the chunk being edited. This problem does not correct itself, and closing and reopening the project took significantly longer than normal. I also now see that the main Electron process is consuming 660+MB rather than the 220+MB I see after restarting the app and opening the project.
This scenario is sometimes hard to replicate, and it does not always produce the same result. In fact, it's hard to predict what will happen other than there will likely be some problem caused by using the up/down and paging keys.
With V11 I have also had a couple of instances on Windows where after leaving the app open for two or more days, the computer locks up and I have to force a power off. Maybe a memory leak?

**Comment by cckozie** [comment] 2016-12-20 23:24
I opened a Psalms project, went to the bottom, and started scrolling by holding down the cursor up key for several seconds, then alternated between holding down the cursor down and cursor up keys. After several seconds of that, several of the chunks got merged together. There are also some extra partial words all in caps showing now in the source text.

![image](https://cloud.githubusercontent.com/assets/8171759/21371809/071d76dc-c6d9-11e6-8da7-20c2f582a89b.png)

Teach me, Yahweh, the way of your statutes, and I will keep them to the end. 34Give me understanding, and I will keep your law; I will observe it with all my heart. 35Guide me in the path of your commandments, for I delight to walk in it. 36Direct my heart toward your covenant decrees and away from unrighteous gain. 37Turn my eyes from looking at worthless things; revive me in your ways. 38Carry out for your servant your promise that you made to those who honor you. 39Take away the insults I dread, for your righteous judgments are good. 40See, I have longed for your instructions; revive me in your righteousness. VAV. 41Yahweh, give me your unfailing love— your salvation, according to your promise; 42then I will have a reply for the one who mocks me, for I trust in your word. 43Do not take the word of truth from my mouth, for I have waited for your righteous decrees. 44I will observe your law continually, forever and ever. 45I will walk securely, for I seek your instructions. 46I will speak of your solemn commands before kings and will not be ashamed. 47I delight in your commandments, which I love dearly. 48I will lift up my hands to your commandments, which I love; I will meditate on your statutes. ZAYIN. 49Call to mind your promise to your servant because you have given me hope. 50This is my comfort in my affliction: that your promise has kept me alive. 51The proud have scoffed at me, yet I have not turned away from your law. 52I have thought about your righteous decrees from ancient times, Yahweh, and I comfort myself. 53Hot anger has taken hold of me because of the wicked who reject your law. 54Your statutes have been my songs in the house where I temporarily live. 55I think about your name during the night, Yahweh, and I keep your law. 56This has been my practice because I have observed your instructions. HETH. 57Yahweh is my portion; I have determined to observe your words. 58I earnestly request your favor with my whole heart; be merciful to me, as your word promised. 59I examined my ways and turned my feet to your covenant decrees. 60I hurry and do not delay to keep your commandments. 61The cords of the wicked have ensnared me; I have not forgotten your law. 62At midnight I rise to give thanks to you because of your righteous decrees. 63I am a companion of all who honor you, to all who observe your instructions. 64The earth, Yahweh, is full of your covenant faithfulness; teach me your statutes. TETH. 65You have done good to your servant, Yahweh, by means of your word. 66Teach me proper discernment and understanding, for I have believed in your commandments. 67Before I was afflicted I went astray, but now I observe your word. 68You are good, and you are one who does good; teach me your statutes. 69The arrogant have smeared me with lies, but I keep your instructions with my whole heart. 70Their hearts are hardened, but I delight in your law. 71It is good for me that I have suffered so that I would learn your statutes. 72Instruction from your mouth is more precious to me than thousands of pieces of gold and silver. YOD. 73Your hands have made and fashioned me; give me understanding so that I may learn your commandments. 74Those who honor you will be glad when they see me because I find hope in your word. 75I know, Yahweh, that your decrees are just, and that in faithfulness you afflicted me. 76Let your covenant faithfulness comfort me, as you promised your servant. 77Show me compassion so that I may live, for your law is my delight. 78Let the proud be put to shame, for they have slandered me; but I will meditate on your instructions. 79May those who honor you turn to me, those who know your covenant decrees. 80May my heart be blameless with respect to your statutes so that I may not be put to shame. KAPH. 81I faint with longing that you might rescue me! I have hope in your word. 82My eyes long to see your promise; when will you comfort me? 83For I have become like a wineskin in the smoke; I do not forget your statutes. 84How long must your servant endure this; when will you judge those who persecute me? 85The proud have dug pits for me, defying your law. 86All your commandments are reliable; those people persecute me wrongfully; help me. 87They have almost made an end to me on earth, but I do not reject your instructions. 88By your steadfast love, keep me alive, so that I may obey your commands. LAMEDH. 89Yahweh, your word stands forever; your word is established firmly in heaven. 90Your faithfulness lasts for all generations; you have established the earth, and it remains. 91All things continue to this day, just as you said in your righteous decrees, for all things are your servants. 92If your law had not been my delight, I would have perished in my affliction. 93I will never forget your instructions, for through them you have kept me alive. 94I am yours; save me, for I seek your instructions. 95The wicked prepare to destroy me, but I will seek to understand your covenant decrees. 96I have seen that everything has its limits, but your commandments are broad, beyond limits. MEM. 97Oh how I love your law! It is my meditation all day long. 98Your commandments make me wiser than my enemies, for your commandments are always with me. 99I have more understanding than all my teachers, for I meditate on your covenant decrees. 100I understand more than those older than I am; this is because I have kept your instructions. 101I have kept my feet back from every evil path so that I might observe your word. 102I have not turned aside from your righteous decrees, for you have instructed me. 103How sweet are your words to my taste, yes, sweeter than honey to my mouth! 104Through your instructions I gain discernment; therefore I hate every false way. NUN. 105Your word is a lamp to my feet and a light for my path. 106I have sworn and have confirmed it, that I will observe your righteous decrees. 107I am very afflicted; keep me alive, Yahweh, as you have promised in your word. 108Yahweh, please accept the freewill offerings of my mouth, and teach me your righteous decrees. 109My life is always in my hand, yet I do not forget your law. 110The wicked have set a snare for me, but I have not strayed from your instructions. 111I claim your covenant decrees as my heritage forever, for they are the joy of my heart. 112My heart is set on obeying your statutes forever to the very end. SAMEKH. 113I hate those who have a double mind, but I love your law. 114You are my hiding place and my shield; I wait for your word. 115Get away from me, you evil doers, so that I may observe the commandments of my God. 116Sustain me by your word so that I may live and not be ashamed of my hope. 117Support me, and I will be safe; I will always meditate on your statutes. 118You reject all those who stray from your statutes, for those people are deceptive and unreliable. 119You remove all the wicked of the earth like slag; therefore I love your solemn commands. 120My body trembles in fear of you, and I am afraid of your righteous decrees. AYIN. 121I do what is just and right; do not abandon me to my oppressors. 122Guarantee the welfare of your servant; do not let the proud oppress me. 123My eyes grow tired as I wait for your salvation and for your righteous word. 124Show your servant your covenant faithfulness, and teach me your statutes. 125I am your servant; give me understanding so that I may know your covenant decrees. 126It is time for Yahweh to act, for people have broken your law. 127Truly I love your commandments more than gold, more than fine gold. 128Therefore I carefully follow all your instructions, and I hate every path of falsehood. PE. 129Your rules are wonderful, that is why I obey them. 130The unfolding of your words gives light; it gives understanding to the untrained. 131I open my mouth and pant, for I long for your commandments. 132Turn to me and have mercy on me, as you always do for those who love your name. 133Direct my footsteps by your word; do not let any sin rule me. 134Redeem me from human oppression so that I may observe your instructions. 135Let your face shine on your servant, and teach me your statutes. 136Streams of tears run down from my eyes because people do not observe your law. TSADHE. 137You are righteous, Yahweh, and your decrees are fair. 138You have given your covenant decrees righteously and faithfully. 139Anger has destroyed me because my adversaries forget your words. 140Your word has been tested very much, and your servant loves it. 141I am insignificant and despised, yet I do not forget your instructions. 142Your justice is forever right, and your law is trustworthy. 143Though distress and anguish have found me, your commandments are still my delight. 144Your covenant decrees are righteous forever; give me understanding that I may live. QOPH. 145I cried out with my whole heart, "Answer me, Yahweh, I will keep your statutes. 146I call to you; save me, and I will observe your covenant decrees." 147I rise before the dawn of the morning and cry for help. I hope in your words. 148My eyes are open before the night watches change so that I might meditate on your word. 149Hear my voice in your covenant faithfulness; keep me alive, Yahweh, as you have promised in your righteous decrees. 150Those who are persecuting me are coming closer to me, but they are far from your law. 151You are near, Yahweh, and all your commandments are trustworthy. 152Long ago I learned from your covenant decrees that you had set them in place forever. RESH. 153Look on my affliction and help me, for I do not forget your law. 154Plead my cause and redeem me; keep me, as you have promised in your word. 155Salvation is far from the wicked, for they do not love your statutes. 156Great are your merciful actions, Yahweh; keep me alive, as you always do. 157My persecutors and my foes are many, yet I have not turned from your covenant decrees. 158I view the treacherous with disgust because they do not keep your word. 159See how I love your instructions; keep me alive, Yahweh, as you have promised by your covenant faithfulness. 160The essence of your word is truth; every one of your righteous decrees lasts forever. SHIN. 161Princes persecute me without cause; my heart trembles, afraid of disobeying your word. 162I rejoice at your word like one who finds great plunder. 163I hate and despise falsehood, but I love your law. 164Seven times a day I praise you because of your righteous decrees. 165Great peace they have, those who love your law; nothing makes them stumble. 166I wait for your salvation, Yahweh, and I obey your commandments. 167I observe your solemn commands, and I love them greatly. 168I keep your instructions and your solemn commands, for you are aware of everything I do. TAV. 169Listen to my cry for help, Yahweh; give me understanding into your word. 170May my plea come before you; help me, as you have promised in your word. 171May my lips pour out praise, for you teach me your statutes. 172Let my tongue sing about your word, for all your commandments are right. 173May your hand help me, for I have chosen your instructions. 174I long for your rescue, Yahweh, and your law is my delight. 175May I live and praise you, and may your righteous decrees help me. 176I have wandered off like a lost sheep; seek your servant, for I have not forgotten your commandments.

**Comment by cckozie** [comment] 2016-12-20 23:27
After the above scenario happened and I captured the data, I scrolled up further using the mouse wheel. After a short time the screen went blank and by looking in task manager I see that the memory usage of the main Electron task has about doubled.

**Comment by cckozie** [comment] 2016-12-20 23:42
[en_psa_text_ulb.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/665039/en_psa_text_ulb.zip)
I don't know if it will help in troubleshooting or not, but this is the project where the chunks got merged. If you open the project and scroll up through the big chunk and keep scrolling (I've been using the mouse wheel to scroll), soon the app will appear to freeze with the data portion of the screen blank. At this point  the memory usage will begin to climb by about 200MB, and the app will take several seconds to respond to any input.

**Comment by cckozie** [comment] 2016-12-21 00:05
Now when I create a new Psalms project it has the chunks merged.

**Comment by cdwhitfield73** [comment] 2016-12-24 01:49
The merged chunks from above is caused by a data issue that is being resolved on the server side.  Further testing has seen a great reduction in the amount of times that scrolling excessively has caused a problem.  I made one more change to the code that runs when scrolling that should further help.  This will appear in build 93.  Since the issues are also created when using the scroll wheel sometimes, it is not tied directly to the arrow keys, so disabling them will not help.  But I think we might be to an "acceptable" place with this issue.

**Closed** 2017-02-09 20:45 UTC
Labels: QA Passed
