### ISSUE TITLE
Wrong error message displayed when attempting to create a door43 accout

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#805] opened 2016-08-19 19:04 UTC
If I try to create a door43 account with an invalid email address (lacking the ".com"), the message I receive indicates that the account already exists rather than that the email address is invalid.

**Comment by cdwhitfield73** [comment] 2017-02-10 21:50
Duplicate of issue #1052.  Closing this one.

**Closed by cdwhitfield73** 2017-02-10 21:50 UTC
