### ISSUE TITLE
Chunk 00.txt fix

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#874] opened 2016-10-28 16:54 UTC
@neutrinog commented on [Tue Jul 05 2016](https://github.com/unfoldingWord-dev/ts-android/issues/1559)

See requirements at https://github.com/unfoldingWord-dev/ts-requirements/issues/153

**Comment by cdwhitfield73** [comment] 2016-10-28 18:40
duplicate of #876.  Closing issue.

**Closed** 2016-10-28 18:41 UTC
