### ISSUE TITLE
Some resource links are not being displayed as links

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1080] opened 2017-02-17 21:47 UTC
![image](https://cloud.githubusercontent.com/assets/8171759/23084504/335814c8-f528-11e6-8140-f4cd88d9fc9b.png)

![image](https://cloud.githubusercontent.com/assets/8171759/23084539/65516ccc-f528-11e6-9ce6-7afc76b7b7ac.png)

**Comment by cdwhitfield73** [comment] 2017-02-18 00:31
Both of these examples are two separate issues.  Currently, there are only two types of links that we support. 1. links that reference sections of tA 2. links that reference other parts of the current project.

The problem with the first example is that it does not fall into one of these two categories.  It is referencing a Bible Word from a note.  I was not told that these type of references existed, so we did not write code to handle them.  It could be done, if @klappy wants this "feature" added, in which case, I would need more info on all the possible format options these notes might appear in.

The problem with the second example is that it should fall into category one, referencing tA, but it is formatted wrong.  This stems from the data and needs to be fixed on that end for the link to get identified correctly and start working.  There are several examples of other links to metonymy that are formatted correctly and working fine.

**Comment by cdwhitfield73** [comment] 2017-02-18 00:33
@ChrisJarka Can you provide some feedback on this issue?  Are there several references to Bible Words in Notes that we should be handling?  Or is this a one time occurrence and maybe is not needed?

Can you have the second example fixed on the data side?  Is it possible to search for other mis-labeled references?

**Comment by ChrisJarka** [comment] 2017-02-18 02:00
For the first example. (See: writing_newevent) should state: (See: Introduction of a New Event) and with the link that it has. The issue is that the title of the tA topic is not rendering instead of the slug.

The (See: [[:en:obe:other:biblicaltimeday]]) issue is something that we should talk about. I'm starting a conversation with my team to get their opinion also.

**Comment by ChrisJarka** [comment] 2017-02-18 02:10
As for example two - the link for Metonomy that is formatted 'incorrectly' is from a tW. translationWords are in git.door43.org and the links were probably changed when the tW pages were moved to the git repo.

The link for Metonymy in the notes (still in the wiki) go to: https://door43.org/en/ta/vol2/translate/figs_metonymy and then they are forwarded to the git Metonymy page at https://git.door43.org/Door43/en-ta-translate-vol2/src/master/content/figs_metonymy.md 

We might want to bring @jag3773 into this conversation, since this could have an effect when the notes are moved to a git repo.

**Comment by ChrisJarka** [comment] 2017-02-21 14:18
The content writers have replied that the link to a tW in a Luke 1:24 note is in error. They are working on correcting any misplaced tW links.
Thank you for bringing this to our attention.

**Comment by cdwhitfield73** [comment] 2017-02-21 16:42
So based on Christine's comments, we do not need to add functionality to handle the "words" link.  It is a mistake and will be removed.  As for the tA reference in Words, these also need to be fixed on the data end if they want them to work in the app.

**Comment by cckozie** [comment] 2017-02-23 15:28
I'm moving this to the backlog lane to retest in the future after the changes have been made server side.

**Comment by jag3773** [comment] 2019-02-08 15:41
Should be handled by #1227

**Comment by neutrinog** [comment] 2019-02-27 00:29
Superseded by #1227

**Closed by neutrinog** 2019-02-27 00:29 UTC
Labels: Blocked, bug
