### ISSUE TITLE
Get build for Linux Mint 

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#548] opened 2016-04-14 16:58 UTC
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [ ] Check that a similar issue has not already been opened.

**Comment by neutrinog** [comment] 2016-04-14 22:47
here are the dependencies for nodegit
```
    linux-vdso.so.1 (0x00007fffe3f16000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fad513d5000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fad510d7000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fad50ec0000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fad50ca3000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fad508ff000)
    /lib64/ld-linux-x86-64.so.2 (0x0000556aa06b9000)
```

**Comment by neutrinog** [comment] 2016-04-14 22:48
@jag3773 can you check on your system and see if you have the dependencies listed above?

**Comment by jag3773** [comment] 2016-04-14 23:29
@neutrinog everything but `linux-vdso.so.1` is on my system

**Comment by jag3773** [comment] 2016-04-14 23:32
However, looking deeper, looks like linux-vdso.so.1 is not a normal file.  Here's what I get when I run `ldd translationStudio`

```
	linux-vdso.so.1 =>  (0x00007ffdb9d33000)
	libnode.so => /home/jesse/Downloads/translationStudio-linux-x64/./libnode.so (0x00007f4dbdc72000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4dbda2f000)
	libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007f4dbd3f2000)
	libgdk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0 (0x00007f4dbd13f000)
	libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007f4dbcf1c000)
	libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f4dbcd0f000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f4dbca04000)
	libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f4dbc7b6000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f4dbc513000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f4dbc2d7000)
	libnotify.so.4 => /usr/lib/x86_64-linux-gnu/libnotify.so.4 (0x00007f4dbc0ce000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f4dbbead000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f4dbbb3a000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f4dbb8e8000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f4dbb6a3000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f4dbb493000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f4dbb288000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f4dbb085000)
	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f4dbae7b000)
	libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007f4dbac77000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f4dbaa65000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f4dba85f000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f4dba654000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f4dba31f000)
	libXtst.so.6 => /usr/lib/x86_64-linux-gnu/libXtst.so.6 (0x00007f4dba119000)
	libgconf-2.so.4 => /usr/lib/x86_64-linux-gnu/libgconf-2.so.4 (0x00007f4db9ee9000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f4db9ce5000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4db9add000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f4db97d4000)
	libnss3.so => /usr/lib/x86_64-linux-gnu/libnss3.so (0x00007f4db949a000)
	libnssutil3.so => /usr/lib/x86_64-linux-gnu/libnssutil3.so (0x00007f4db926e000)
	libsmime3.so => /usr/lib/x86_64-linux-gnu/libsmime3.so (0x00007f4db9041000)
	libnspr4.so => /usr/lib/x86_64-linux-gnu/libnspr4.so (0x00007f4db8e04000)
	libffmpeg.so => /home/jesse/Downloads/translationStudio-linux-x64/./libffmpeg.so (0x00007f4db8a44000)
	libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007f4db8753000)
	libcups.so.2 => /usr/lib/x86_64-linux-gnu/libcups.so.2 (0x00007f4db84df000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4db82db000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f4db80b0000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4db7dac000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4db7aa6000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4db788f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4db74ca000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4dbef15000)
	libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f4db72b5000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f4db70b1000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f4db6e09000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f4db6be2000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f4db69df000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f4db67d6000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f4db65b6000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4db639d000)
	libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007f4db6194000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f4db5f70000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f4db5d55000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f4db5b4c000)
	libdbus-glib-1.so.2 => /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2 (0x00007f4db5925000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f4db56e6000)
	libplc4.so => /usr/lib/x86_64-linux-gnu/libplc4.so (0x00007f4db54e1000)
	libplds4.so => /usr/lib/x86_64-linux-gnu/libplds4.so (0x00007f4db52dd000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f4db5095000)
	libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007f4db4dd7000)
	libavahi-common.so.3 => /usr/lib/x86_64-linux-gnu/libavahi-common.so.3 (0x00007f4db4bca000)
	libavahi-client.so.3 => /usr/lib/x86_64-linux-gnu/libavahi-client.so.3 (0x00007f4db49b9000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f4db4763000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f4db455f000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f4db4358000)
	libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f4db4151000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f4db3e85000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f4db3c56000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f4db3a52000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f4db3846000)
	libgcrypt.so.11 => /home/jesse/Downloads/translationStudio-linux-x64/./libgcrypt.so.11 (0x00007f4db35c7000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f4db33b3000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f4db3170000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f4db2f4a000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f4db2d45000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f4db2b40000)
```

**Comment by tjklemz** [comment] 2016-04-15 03:13
linux-vdso is injected by the kernel.

**Comment by neutrinog** [comment] 2016-05-12 17:57
duplicate of #481

**Closed** 2016-05-12 17:58 UTC
Labels: duplicate
