### ISSUE TITLE
target language update fails ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#1100] opened 2017-03-04 14:05 UTC
Notes
======
target language update fails after 3 qaa languages

Environment
======
Environment Key | Value
:--: | :--:
Version |11.0.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.10586
Architecture | x64

Log History
======
```javascript
2017-03-04 15:53:20 I/ts-dashboard.html:1119:4: Feedback Sent
	https://api.github.com/repos/unfoldingWord-dev/ts-desktop/issues/1099
2017-03-04 15:54:48 E/ts-dashboard.html:447:3: Update Failed
	Error: read ECONNRESET
2017-03-04 15:56:7 E/ts-dashboard.html:447:3: Update Failed
	SyntaxError: Unexpected end of JSON input

```

**Comment by cdwhitfield73** [comment] 2017-03-06 16:55
Based on comments in slack, this issue was caused by slow or unreliable internet connection and has been resolved.  Closing issue.

**Closed** 2017-03-06 16:55 UTC
Labels: 11.0.0, bug report
