### ISSUE TITLE
Wrong error message when creating an account on door43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1052] opened 2017-01-18 21:01 UTC
When an invalid email address (no @) is entered on the form to create a door43 account, the message returned is "Account already exists for this username or this email address" even though the account does not actually exist. (Was able to create it with all info the same except info but with a valid email address)

**Comment by cdwhitfield73** [comment] 2017-01-18 21:07
This is basically a duplicate of issue #805

**Comment by cdwhitfield73** [comment] 2017-02-10 21:50
It will now give more specific messages "Account already exists for this username" or "Invalid email address".  Currently, Door43 is allowing accounts with duplicate email addresses, so this is not producing an error.  This is an issue on the server, not in the app.

**Closed** 2017-04-18 19:05 UTC
Labels: bug, QA Passed
