### ISSUE TITLE
Some source content (English) is not being imported for tW

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/ts-desktop#378] opened 2016-02-23 15:47 UTC
As per a helpdesk question on 2/23 by Eric Steggerda. In "Apollos" the tW ends with "Paul emphasized how he..." and cuts off mid-sentence. In the source (https://door43.org/en/obe/other/apollos) the very next word is "(Paul)". It would appear that the () is keeping the rest of the tW from showing up.

**Comment by jag3773** [comment] 2016-02-23 16:56
The problem is the parenthesis, looking into a fix.

**Comment by jag3773** [comment] 2016-02-23 17:05
Fixed in https://github.com/unfoldingWord-dev/tools/commit/dfd3c7ab2b25f46825bdd255e60d2ee36d1e3453

**Closed by jag3773** 2016-02-23 17:05 UTC
Labels: bug

**Comment by ChrisJarka** [comment] 2017-01-19 19:29
This issue has shown up in tS-D v11 build 110.

Here is a screen shot from the program:

![tw missing content v11b110](https://cloud.githubusercontent.com/assets/9850185/22121876/a4cb2dd4-de53-11e6-9e97-63277923a77d.png)


Here is a screen shot of the word in gogs. Everything in highlight is missing. Arrow points to the parenth.

![tw acknowledge from gogs](https://cloud.githubusercontent.com/assets/9850185/22121880/aa265272-de53-11e6-8068-79d9aaee6884.png)
