### ISSUE TITLE
change tstudio import to use git to merge changes

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#366] opened 2016-02-16 21:11 UTC
(We need the corresponding work done in desktop that was done in Android. https://github.com/unfoldingWord-dev/ts-android/issues/1255)

This will solve issues with users' content getting overwritten during an import. See #312 

See merge spec https://github.com/unfoldingWord-dev/ts-requirements/wiki/Importing-a-Target-Translation#tstudio-archive

**Comment by RRohrssen** [comment] 2016-02-16 21:11
Blocked by #304.

**Comment by RRohrssen** [comment] 2016-02-16 21:12
https://cloud.githubusercontent.com/assets/166412/12929482/cabb023a-cf27-11e5-9540-201408400fef.jpg

**Comment by RRohrssen** [comment] 2016-02-16 21:14
![merge](https://cloud.githubusercontent.com/assets/15789352/13091261/e74c1914-d4bf-11e5-989f-38eab6b1dac0.jpg)

**Comment by neutrinog** [comment] 2016-02-16 21:54
Update on the "rolling back" part. I think we could leave it and then use the git conflict code that will have been inserted into chunk for rendering in the ui.

**Comment by neutrinog** [comment] 2016-02-18 17:12
Details about how to perform the merge can be found in https://github.com/unfoldingWord-dev/ts-requirements/wiki/Importing-a-Target-Translation#tstudio-archive

**Comment by neutrinog** [comment] 2016-03-31 17:24
android code for reference is at https://github.com/unfoldingWord-dev/ts-android/blob/master/app/src/main/java/com/door43/translationstudio/core/TargetTranslation.java#L1102

**Comment by cdwhitfield73** [comment] 2016-04-15 17:34
Thomas and I are setting up a git merge function now that can be used on the new import features when needed.

**Comment by neutrinog** [comment] 2016-05-06 20:56
@cdwhitfield73  The merging is not working according to the spec. Here's are the steps I'm taking.

1. create a new translation
2. edit the first two frames
3. backup the translation
4. start the same translation again
5. edit the second and third frames
6. merge the backup into the translation

The result should be frame 1, frame 2 (with merge conflict code), frame 3.

However the result I'm getting is frame 1 (missing), frame 2 (not merged), frame 3.

![20160506-135236](https://cloud.githubusercontent.com/assets/166412/15085878/da1a0ad8-1391-11e6-80f5-5890ef3b966d.png)

here's what the result should look
![screenshot_2016-05-06-13-53-49](https://cloud.githubusercontent.com/assets/166412/15085918/2df20174-1392-11e6-9298-6ab36031fe72.png)

**Comment by neutrinog** [comment] 2016-05-06 21:20
btw it's failing on linux (Debian).

**Comment by tjklemz** [comment] 2016-05-06 21:38
@neutrinog there will not be merge conflicts. We are doing a union. We can do a prefer ours, theirs, or union. We are unable for the moment to deal with conflicts due to issues with Nodegit. The union seems to do what we want for now.

I can confirm that the merging works properly on Mac and Windows. I will have to test on Linux. Can you post the Error?

**Comment by tjklemz** [comment] 2016-05-06 21:39
@neutrinog what do you mean by "4. start the same translation again"? I feel like perhaps it is working but you have a different workflow.

**Comment by neutrinog** [comment] 2016-05-06 21:49
I delete the translation then create it again from scratch so it has a fresh git history.

**Comment by tjklemz** [comment] 2016-05-06 21:54
For the record, it looks like everything is working on Mac/Windows, and Linux is the only one with unexpected results? (And those screenshots were from Debian Linux.) This correct?

**Comment by neutrinog** [comment] 2016-05-06 22:01
for posterity: We do not want to prefer one or the other. For now a union will suffice, but eventually we'll need to have the merge conflict code in there as well. 

For details see https://github.com/unfoldingWord-dev/ts-requirements/wiki/Importing-a-Target-Translation#merge-conflicts and https://github.com/unfoldingWord-dev/ts-requirements/wiki/Publishing#merge-conflicts

**Comment by neutrinog** [comment] 2016-05-07 00:19
I'm having the same issue on OSX as well. @cckozie I'm sending you the builds for today. When you get a chance can you check this out?

**Comment by cckozie** [comment] 2016-05-18 19:59
I am having the same problem as Joel specified above on both Windows and OSX. The steps I took:
1. Created a new project (Philemon, English Demo1 target, English ULB source)
2. Copied the text from chunk 1 into the target frame.
3. Did a Backup of the project.
4. Deleted the project.
5. Repeated step 1.
6. Copied the text from chunks 2 & 3 into the target frames.
7. Imported the project saved in step 3.
At this point chunk 1 target frame is empty.
I then Restored the project save in step 3 just to verify that the text for chunk 1 was there, and it was.

**Comment by cdwhitfield73** [comment] 2016-05-19 18:17
Cannot duplicate this error in development mode.  Could be something specific to the build

**Comment by neutrinog** [comment] 2016-05-19 20:07
@cdwhitfield73 you can checkout the release-8.0 branch and create a build from that. `gulp build --win`

**Comment by cdwhitfield73** [comment] 2016-05-23 20:59
Just created a build manually from the version 8 branch and ran through these steps...and the project merged successfully with all 3 chunks of data.  Still cannot duplicate this issue.

**Comment by neutrinog** [comment] 2016-05-24 14:56
@cdwhitfield73 please provide your build to @cckozie and myself via dropbox.

**Comment by cckozie** [comment] 2016-05-24 20:53
This is still failing in the 8.0.3 build. Here are the files I'm using to test:
[en-x-demo1_phm_text_ulb-B.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/280496/en-x-demo1_phm_text_ulb-B.zip)
[en-x-demo1_phm_text_ulb-C.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/280497/en-x-demo1_phm_text_ulb-C.zip)

**Comment by cckozie** [comment] 2016-05-26 18:06
Working as expected on both Windows and Mac

**Closed** 2016-05-31 13:53 UTC
Labels: QA Passed
