### ISSUE TITLE
One field is empty. In tN, UL...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#1205] opened 2017-11-07 11:00 UTC
Notes
======
One field is empty. In tN, ULB, chunk Luke 6:35-36, 1st note. The title is there, but the body of the note is empty.

Environment
======
Environment Key | Value
:--: | :--:
Version |11.1.0
Operating System | Windows_NT
Platform | win32
Release | 10.0.15063
Architecture | x64

Log History
======
```javascript
2017-11-02 17:21:12 I/ts-dashboard.html:1161:4: Feedback Sent
	https://api.github.com/repos/unfoldingWord-dev/ts-desktop/issues/1204
2017-11-02 19:51:37 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-11-03 11:50:20 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-11-03 14:22:25 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-11-03 19:41:11 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-11-03 22:4:23 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-11-03 22:53:12 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-11-03 23:7:41 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-11-03 23:16:28 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-11-04 11:58:26 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-11-04 13:21:50 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-11-04 13:33:47 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-11-04 15:7:28 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-11-05 20:34:48 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1
2017-11-07 11:53:24 I/ts-dashboard.html:1372:3: 
	Git Version 2.9.2.windows.1

```

**Comment by ChrisJarka** [comment] 2017-11-07 13:01
For the note: "your reward will be great" there is this information - "you will receive a great reward" or "you will receive good payment" or "you will get good gifts because of it"

Version 11.1 (Build 132)

**Comment by neutrinog** [comment] 2019-02-27 00:18
closing this as unable to reproduce.

**Closed by neutrinog** 2019-02-27 00:18 UTC
Labels: 11.1.0, bug report
