### ISSUE TITLE
Build nodegit binaries for linux and win32

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#409] opened 2016-03-03 15:45 UTC
From Jelle Huisman
![ts-hangs-on-git](https://cloud.githubusercontent.com/assets/15789352/13499583/9bb45284-e124-11e5-8439-220a19b81afa.png)

**Comment by jellehuisman** [comment] 2016-03-03 16:59
FYI: I'm running LinuxMint 17.3 I happen to have git installed, but I shouldn't have to, from what I understand.

**Comment by RRohrssen** [comment] 2016-03-03 17:12
This seems to be an issue when compiled on different Linux variants. Joel is thinking that he needs to create a different Linux install and compile on that platform.

**Comment by jellehuisman** [comment] 2016-03-04 13:07
I have just tried it on Fedora 23 (on a Live-USB stick) and ts starts without problems. But given that Ubuntu-based distributions (such as LinuxMint) are far more popular it should work there as well. Thank you for looking into this and I'd be happy to help by testing something (if needed.)

**Comment by neutrinog** [comment] 2016-03-24 16:56
duplicate of #481

**Closed by neutrinog** 2016-03-24 16:56 UTC
Labels: bug
