### ISSUE TITLE
RCT needs to merge multiple work files together

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#575] opened 2016-05-05 16:40 UTC
George is a project manager that needs to merge the work together that was completed by his team. He is unsure how to proceed. He asks Peter, acting as an RCT to help out. Peter wants a way to easily get the files in one location without having to track them all down manually. Ideally he wants his tS on his device to be able to pull them all down to his device from the server and allow him to decide which to merge together. Once they are merged together they can do a read through to ensure all is well, and upload final merge when ready.

**Comment by neutrinog** [comment] 2016-05-06 21:39
this is basically a duplicate of #453

**Closed by neutrinog** 2016-05-06 21:39 UTC
