### ISSUE TITLE
Implement new workflow for updating sources

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#880] opened 2016-10-28 17:17 UTC

**Comment by cdwhitfield73** [comment] 2016-11-03 21:13
@klappy - @cckozie just showed me the "plan" that they came up with for the new work flow for updating sources.  Besides adding a new screen for seeing all available downloads right after updating, it also includes some significant changes to the source selection box in a project.  To fully implement exactly what he proposed, I am currently giving this issue an 8 for story points and need to warn you that I do not feel confident I can complete this task by the end of this sprint.  However, I have made a few suggestions for some minor changes (including modifying the look of the UI) that would reduce the time needed to implement.  If these changes are acceptable, we could bring this issue down to a 5 and have a better chance of completing it this sprint. Koz has the details of my suggestions.

**Comment by cdwhitfield73** [comment] 2016-11-19 00:13
This issue will be for the "basic" setup of the new workflow.  I will create separate issues for the "advanced" features that aren't done yet and will need extra time. (Examples: Cancel option on downloading popups, progress indicators (2 of 67, etc.))

**Comment by cckozie** [comment] 2016-11-22 15:53
Choose the View New and Updated Source Texts option on the Update Options menu.
Search for and choose a language
Click the <-- by the language to return to the previous screen
The search filter is still in effect at this point but should not be

**Comment by cdwhitfield73** [comment] 2016-11-22 20:08
Issue above is fixed in build 73

**Comment by cckozie** [comment] 2016-11-22 21:27
Get the error msg "An error occurred while downloading" when attempting to download አማርኛ(am)
for OBS Words. Nothing related shows in the console.

**Comment by cckozie** [comment] 2016-11-22 21:38
If I have multiple projects selected for download and one of them fails, it would be nice:
1. If the error message indicated which one failed.
2. If the failure did not prevent the other selected projects from downloading.

**Comment by cckozie** [comment] 2016-11-23 16:24
Since we are not able to show the user which sources are new and which have updates available, we should change the verbiage on the Update Options menu.
Replace "Check for New and Updated Source Texts" with "Download List of Available Source Texts".
Replace "View New and Updated Source Texts" with "View Downloaded List of Available Source Texts". (Pending approval by CJ)

**Comment by cdwhitfield73** [comment] 2016-11-23 16:29
@cckozie I agree with most of your suggestion above, except for the word "Downloaded" in the second option.  As I mentioned the other day, you can view the list of available texts right out of the box, whether you have run the update or not, so I suggest "View List of Available Source Texts".  Now that I think about it, perhaps the first one should be "Update List of Available Source Texts" which is more accurate and gives the user the sense that the list already exists at some level, whether they choose that option or not.

**Comment by ChrisJarka** [comment] 2016-11-25 17:17
@cdwhitfield73 so as I understand the Update Options menu -

- the 1st option (Update List of Available Source Texts) starts the action of updating the list. That is all.
- the 2nd option (Download Available Source Texts) starts the menus of choosing the available texts to download.

If so, I think what is in the parenthesis says what the end user will experience.

Question - what happens if the end-user does the 2nd option and not the 1st?

**Comment by cdwhitfield73** [comment] 2016-11-25 19:17
Changed text on Update Options menu per discussion with Christine.
Added results of download to list (green checks for successful downloads and red warning icons for failures, clicking on icon will display reason for failure). Results of downloads persist while in Source Text module.
Added proper error message for download attempts of OBS translationWords that don't exist, discussing with Jesse why those are in the list at all.

**Comment by cckozie** [comment] 2016-11-30 14:00
On the source selection screen described on the last page of the PPT, change the wording from "Check for New and Updated Sources" to "Exit to Update Source Text List". Clicking this link closes the project and runs the same process that is run by selecting the first option on the Update Options menu.

**Comment by cckozie** [comment] 2016-12-01 17:59
Problems with dialogs presented when choosing a source text for a new project when following this procedure in build 76. (looks like its actually running the update source texts process)
Deleted the hidden translationStudio folder
Started tS and logged into door43 account
Ran the "Update List of Available Source Texts" option
Created a new English Philippians project
Selected English ULB as the source and clicked CONFIRM
The dialog presented was the "Updating List of Source Texts" one
Later I get the "No new Source Texts have been added" message

**Comment by cckozie** [comment] 2016-12-01 18:44
I ran the above scenario except for running the Update list of sources. Same result.

**Comment by cckozie** [comment] 2016-12-01 19:01
I think the CANCEL during the update process is also going to cause some user freak-outs. On my "field-like" Windows machine, when I click CANCEL in the update process, the screen goes "blank" for 12 seconds, then for another 23 seconds it shows the home screen with no projects visible. At this point most users will most likely think they have lost all of their projects.
Would it be possible to set a flag in local or session storage when executing the CANCEL, and then when the page reloads check the flag and display some sort of "working on it" dialog until we've gotten through all of the initialization steps?

**Comment by cdwhitfield73** [comment] 2016-12-01 19:25
The above problem has been found and fixed.  Retest again when you get build 77.

**Comment by cckozie** [comment] 2016-12-02 16:20
The last issue is fixed in build 77. More testing to do.

**Comment by cckozie** [comment] 2016-12-08 21:11
NOTE FOR TESTING:
To test for new resources:
Delete the appropriate row from the resources table in the index db.
Delete the corresponding resource from the hidden resource_containers folder.
Delete the corresponding resource from 
C:\Program Files (x86)\translationStudio\resources\app\src\index\resource_containers

**Comment by cckozie** [comment] 2016-12-08 22:12
Here's an interesting one to consider. If there is a source text for a project but no source text for the associated questions project, the source language still appears as available when creating the project. When it is selected the refresh icon is displayed, but the user is not forced (or warned) to do the update (actually a download). When the user CONFIRMS and the desired resource does not exist yet on the user's machine, we should probably put up a different dialog than the Loading source one to inform them that they need to click the refresh icon and then send them back to the source selection dialog.

**Comment by cckozie** [comment] 2016-12-09 17:25
After talking with CW, a better way to address this would be to filter the sources by project type, and if the source for questions was available only on-line, then it would show up in that group rather than in the available group. Talking with Klappy to see if this should be an enhancement request instead.

**Comment by cckozie** [comment] 2016-12-09 18:30
Created a new issue to deal with the above two comments as an enhancement.

**Comment by cckozie** [comment] 2016-12-14 21:06
@cdwhitfield73 I don't know that this is worth failing the issue, but it feels a little strange.
On my slower machine - while downloading the ULB for Psalms, the % complete remains at 0 for about 8 seconds, then jumps to 50%, and the download finishes before the % gets updated again. Seems like it would make more sense to update it on ever x% or on a 1 second timer. I see a similar pattern when downloading Jude, although it's more like 4 seconds before the 1st update.
If I download both the ULB and UDB for Matthew, Mark, and Luke as a single download, the updates come about every 14%, but occur at about 8,11, 16, 18, 25, 27, and 35 seconds.

**Comment by cdwhitfield73** [comment] 2016-12-14 22:30
Well, if you fail it, there isn't much I can do to fix it.  The only way to calculate a percentage for this feature is based on the number of downloads it is doing.  There is no way to know how big any given file is or how long it will take to download, only that it is finished or not.  It includes whether or not it needs to update the "words" container and will never show 100% because at that point it is done!  So in the Psalms example, it is downloading 2 things (Psalms and Words).  While Psalms is downloading, nothing is complete yet, so 0%.  Psalms takes awhile and then it shows 50% (1 of 2 done).  Then Words updates and it's finished.  In the last example, there are 7 containers downloaded, including Words.  So as each one completes, 14% is added.

**Comment by cckozie** [comment] 2016-12-14 22:54
OK, that makes sense.

**Comment by cckozie** [comment] 2016-12-28 16:56
There is an inconsistency with updating UDB resources. Here is the process I followed and what I observed:
Deleted the English ULB, UDB, tN, and tQ entries for James from the index db, and from both resource_container folders.
Ran the Update List of Available Source Texts option. It reported 4 new source texts available.
Created a new James project in non-gateway mode. English ULB appeared as Availabe Online as expect.
Ran the ULB update and opened the project. Notes and Questions appear as resources, but UDB does not, nor does it appear as an option to add an Available or Available Online source text. It appears that the only way to make it available to the project is to go the Update menu and run the Download Available Source Texts option for the English UDB for James.
The same result occurs when running tS in Gateway mode.
When creating a UDB project, the UDB does appear as an option under Available Online source texts.

**Comment by ChrisJarka** [comment] 2016-12-28 17:30
hmmm - sounds like the UDB ended up in the source text "list" and not in the resources "list."

**Comment by cckozie** [comment] 2016-12-28 22:01
If the UDB is not available as a resource when a project is created, it cannot be added to the project even after it becomes available and is downloaded.

**Comment by cdwhitfield73** [comment] 2016-12-28 22:09
Please provide more information to the above statement (the steps that were taken) so I understand.  If you open a project (ULB) and there is no UDB, then it will not populate the resource with UDB.  If you then download UDB from the source selector with the project open, it will not refresh the resources, but if you go to the home page and re open the project, then UDB resources should show up.

**Comment by cckozie** [comment] 2016-12-28 22:23
Created the project (ULB) when UDB was not available. Did a Update List of Available Resources, then went into the Download Available Source Texts, chose By Book, then chose the book, then selected English UDB and downloaded it. Then reopened the project and noticed that the UDB was still not showing. I then created a second ULB project for the book and saw that the UDB did show up as a resource in it. 
The UDB does not show up as an option in the source selection dialog for a ULB project.

**Comment by cdwhitfield73** [comment] 2016-12-29 16:51
Changed it back to the way it was before: When downloading or updating the ULB source, it will now also download or update the UDB as well (along with tN and tQ).

**Comment by cckozie** [comment] 2016-12-29 17:41
Regarding the issue with the UDB not showing up if it was not available when the project was created:
The behavior observed was actually caused by the fact that I had specified an imported custom source text for this project. Here is the behavior I observe when that is the case:
In order to have all of the resources displayed, the language slug must be "en" and the resource slug must be "ulb" for the source language currently displayed.
If the language slug is "en" and the resource slug is not "ulb", then the only resources displayed are Notes, Questions, and Words.
If the language slug is not "en" and the resource slug is not "ulb", then the only resource displayed is Words.
I receive an error anytime I try to import a text where the language slug is not "en" and the resource slug is "ulb". Is that the desired behavior?

**Comment by cckozie** [comment] 2016-12-29 18:35
Christine's feedback is to show all available resources matching the language only when the source text is designated as ULB.

**Comment by cdwhitfield73** [comment] 2016-12-29 21:31
The code has been changed to match the new desired outcomes.  Here is a brief summary of how it now works.

The notes and questions will only show up if the project is ULB or OBS AND there are matching notes or questions to that language/project combo.

The udb resource will only show up if the project is ULB and there is a matching resource for the language/project combo.

The words resource will show up based on whether that source calls for them in its "config.yml" file.  This is completely data driven and the app has no filters to prevent this.  Currently, the UDB sources call for the same word list as the ULB, so they will show up.  Phil is removing the links from the api to address this issue.  Koz - this also impacts whether you see words when you "create" a copy of a container to import.  Based on which container you copy and the state of its config file.

**Closed** 2017-02-09 20:46 UTC
Labels: QA Passed
